# Exported from Render on 2026-08-15T10:26:07Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: biomedical
      runtime: node
      repo: https://github.com/Kenn555/biomedical
      plan: free
      region: ohio
      buildCommand: bun install
      startCommand: bun run start
      autoDeployTrigger: commit
